@echo off
rem
rem Environment setup script generated by cscript configure.vbs --with-DDK=C:\WinDDK\7600.16385.1 --with-MinGW-w64=C:\lib\mingw\mingw64 --with-MinGW32=C:\lib\mingw\mingw32 --with-libSDL=C:\lib\SDL\x64\SDL-1.2.15 --with-openssl=C:\lib\OpenSSL\x64 --with-openssl32=C:\lib\OpenSSL\x86 --with-libcurl=C:\lib\curl\x64 --with-libcurl32=C:\lib\curl\x86 --with-Qt5=C:\Qt\5.6.3\msvc2010_64 --with-libvpx=C:\lib\libvpx --with-libopus=C:\lib\libopus --with-python=C:/Python27
rem
set KBUILD_TARGET_ARCH=amd64
set KBUILD_HOST_ARCH=amd64
set KBUILD_PATH=C:/Users/atatat/Projects/VirtualBox-6.1.18/kBuild
set PATH=C:/Users/atatat/Projects/VirtualBox-6.1.18/kBuild/bin/win.amd64;%PATH%
set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7/IDE;
set PATH=%PATH%;C:\Users\atatat\Projects\VirtualBox-6.1.18/tools/win.amd64/bin;
